### ISSUE TITLE
About inconvenience for XXMI (not issue)

### ISSUE THREAD

**Issue by Promedio** [SpectrumQT/XXMI-Installer#2]
## Confusing "installer"

The XXMI installer is not an "installer" in the traditional sense of the word, but more like some kind of automated decompression program. When I couldn't find it in the application list, I had a vague feeling that it was more of a malicious program. It doesn't seem to create the correct registry or use AppData; Would you consider using MSIX if so?

### "Installation" behavior is not satisfactory

I mean the "install" behavior doesn't even get the game's installation directory automatically and it's somehow more burdensome to use.

## More cumbersome steps

Does XXMI support command line startup? If not, do you have to go through the launcher every time you start the game? That's too bad and it's a shame that WWMI has compromised on this.

**Comment by SpectrumQT** [comment]
Yes, installer is first and foremost launcher self-updater app, with extra GUI step for manual configuration of update path for first installation. Launcher is a portable app, and it doesn't require any registry records. If installer gets launcher downloaded in specified location, it gets its job done.

And yes, launcher supports command line startup of requested XXMI package. Use 3 dots button on Start button to create shortcut automatically. Args are `--nogui --xxmi WWMI`.
